# Generated by Django 6.0.4 on 2026-04-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(default='#1B263B', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('event', 'Event'), ('closure', 'Closure')], default='event', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('reporterName', models.CharField(max_length=100)),
                ('reporterPhone', models.CharField(max_length=20)),
                ('reporterId', models.CharField(max_length=50)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('itemName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('dateReported', models.DateField(auto_now_add=True)),
                ('dateOfIncident', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lostfound/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('solved', 'Solved'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('handlerNotes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
