# Generated by Django 6.0.4 on 2026-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calendarevent_lostfounditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCaseRecord',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('cleared', 'Cleared'), ('flagged', 'Flagged'), ('under_review', 'Under Review')], default='under_review', max_length=20)),
                ('details', models.TextField()),
                ('requestId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('ready_to_pickup', 'Ready to Pick Up'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('history', models.CharField(default='clear', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('civilStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('validId', models.CharField(blank=True, max_length=50, null=True)),
                ('validIdNo', models.CharField(blank=True, max_length=50, null=True)),
                ('payment', models.CharField(blank=True, max_length=20, null=True)),
                ('copies', models.CharField(blank=True, max_length=10, null=True)),
                ('pickupDeadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
