# Generated by Django 6.0.4 on 2026-04-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documentcaserecord_documentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('crime', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('details', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('linkedReports', models.JSONField(blank=True, default=list)),
                ('charges', models.TextField(blank=True, null=True)),
                ('penalty', models.TextField(blank=True, null=True)),
                ('complainant', models.CharField(blank=True, max_length=100, null=True)),
                ('respondent', models.CharField(blank=True, max_length=100, null=True)),
                ('dateResolved', models.DateField(blank=True, null=True)),
                ('mediator', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('priorOffenses', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('served', 'Served'), ('canceled', 'Canceled')], default='waiting', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('chiefComplaint', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('queueDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('progress', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('contractor', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('images', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
