# Generated by Django 6.0.4 on 2026-04-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
