# Generated by Django 6.0.4 on 2026-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staffaccount_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
