# Generated by Django 6.0.4 on 2026-04-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_staffaccount_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffaccount',
            old_name='active',
            new_name='is_online',
        ),
    ]
