# Generated by Django 6.0.4 on 2026-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_active_staffaccount_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='gcashProof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='idPhoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='selfiePhoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
