# Generated by Django 6.0.4 on 2026-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_documentrequest_email_documentrequest_gcashproof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='yearsResiding',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
