# Generated by GitHub Copilot on 2026-04-25

import uuid
from django.db import migrations, models


def drop_and_recreate_staff_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS api_passwordresetcode;")
        cursor.execute("DROP TABLE IF EXISTS api_auditlog;")
        cursor.execute("DROP TABLE IF EXISTS api_staffaccount_groups;")
        cursor.execute("DROP TABLE IF EXISTS api_staffaccount_user_permissions;")
        cursor.execute("DROP TABLE IF EXISTS django_admin_log;")
        cursor.execute("DROP TABLE IF EXISTS api_staffaccount;")

    StaffAccount = apps.get_model("api", "StaffAccount")
    PasswordResetCode = apps.get_model("api", "PasswordResetCode")
    AuditLog = apps.get_model("api", "AuditLog")

    schema_editor.create_model(StaffAccount)
    schema_editor.create_model(PasswordResetCode)
    schema_editor.create_model(AuditLog)

    try:
        LogEntry = apps.get_model("admin", "LogEntry")
    except LookupError:
        LogEntry = None

    if LogEntry:
        schema_editor.create_model(LogEntry)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_documentrequest_email_documentrequest_gcashproof_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="staffaccount",
                    name="id",
                    field=models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            drop_and_recreate_staff_tables,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
