# Generated by GitHub Copilot on 2026-04-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_documentrequest_notes_documentrequest_yearsresiding"),
        ("api", "0010_reset_staffaccount_uuid"),
    ]

    operations = []
