# Generated by Django 6.0.4 on 2026-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_documentrequest_statusupdatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('ready_to_pickup', 'Ready to Pick Up'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
