# Generated by Django 6.0.4 on 2026-05-02 02:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_project_milestones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caserecord',
            options={'ordering': ['-case_date']},
        ),
        migrations.AlterModelOptions(
            name='lostfounditem',
            options={'ordering': ['-date_reported']},
        ),
        migrations.RenameField(
            model_name='caserecord',
            old_name='date',
            new_name='case_date',
        ),
        migrations.RenameField(
            model_name='caserecord',
            old_name='dateResolved',
            new_name='date_resolved',
        ),
        migrations.RenameField(
            model_name='lostfounditem',
            old_name='dateReported',
            new_name='date_reported',
        ),
        migrations.RenameField(
            model_name='lostfounditem',
            old_name='handlerNotes',
            new_name='handler_notes',
        ),
        migrations.RenameField(
            model_name='lostfounditem',
            old_name='isAnonymous',
            new_name='is_anonymous',
        ),
        migrations.RenameField(
            model_name='lostfounditem',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='lostfounditem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='linkedReports',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='priorOffenses',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='dateOfIncident',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='reporterId',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='reporterName',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='reporterPhone',
        ),
        migrations.AddField(
            model_name='caserecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caserecord',
            name='crime_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caserecord',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='subject_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caserecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='date_of_incident',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='reporter_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='complainant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='mediator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='respondent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='caserecord',
            table='case_records',
        ),
        migrations.AlterModelTable(
            name='lostfounditem',
            table='lost_found_items',
        ),
        migrations.CreateModel(
            name='CasePriorOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('offense_date', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caserecord')),
            ],
            options={
                'db_table': 'case_prior_offenses',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reporter_name', models.CharField(max_length=200)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField()),
                ('incident_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='new', max_length=30)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('incident_time', models.CharField(blank=True, max_length=20, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('suspect_name', models.CharField(blank=True, max_length=200, null=True)),
                ('suspect_description', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True)),
                ('evidence_photo_count', models.IntegerField(default=0)),
                ('victims_involved', models.CharField(blank=True, max_length=200, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('reporter_relation', models.CharField(blank=True, choices=[('Victim', 'Victim'), ('Witness', 'Witness'), ('Concerned Neighbor', 'Concerned Neighbor')], max_length=100, null=True)),
                ('source', models.CharField(choices=[('staff', 'Staff'), ('public', 'Public')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseLinkedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caserecord')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident')),
            ],
            options={
                'db_table': 'case_linked_reports',
                'unique_together': {('case', 'incident')},
            },
        ),
    ]
