# Generated by Django 6.0.4 on 2026-05-02 03:18

import api.report_handler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_caserecord_options_alter_lostfounditem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='id',
            field=models.CharField(default=api.report_handler.models.generate_case_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.CharField(default=api.report_handler.models.generate_incident_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='id',
            field=models.CharField(default=api.report_handler.models.generate_lf_id, max_length=20, primary_key=True, serialize=False),
        ),
    ]
