# Generated by Django 6.0.4 on 2026-05-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_caserecord_id_alter_incident_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='evidence_photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
