# Generated by Django 6.0.4 on 2026-05-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_incident_evidence_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('post', 'Post'), ('solved', 'Solved'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
