# Generated by Django 6.0.4 on 2026-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_lostfounditem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reporter_relation',
            field=models.CharField(blank=True, choices=[('Victim', 'Victim'), ('Witness', 'Witness'), ('Concerned Neighbor', 'Concerned Neighbor'), ('Barangay Official', 'Barangay Official'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
