# Generated by Django 6.0.4 on 2026-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_incident_reporter_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('post', 'Post'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
