# Generated by Django 6.0.3 on 2026-05-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_landing_page_clinic_consultation_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseprioroffense',
            name='case',
        ),
        migrations.DeleteModel(
            name='CaseLinkedReport',
        ),
        migrations.DeleteModel(
            name='CasePriorOffense',
        ),
    ]
