from rest_framework import viewsets, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from .models import Incident
from .serializers import IncidentSerializer
from .cleanup import cleanup_expired_reports


class IncidentViewSet(viewsets.ModelViewSet):
    serializer_class = IncidentSerializer

    def get_queryset(self):
        cleanup_expired_reports()
        return Incident.objects.all().order_by("-created_at")

    def get_permissions(self):
        if self.action in ["list", "retrieve", "create"]:
            return [AllowAny()]
        return [IsAuthenticated()]


@api_view(["POST"])
@permission_classes([AllowAny])
def public_report_view(request):
    """Public incident reporting endpoint"""
    cleanup_expired_reports()
    # Make a copy to avoid modifying the original request
    data = request.data.copy() if hasattr(request.data, 'copy') else dict(request.data)

    # Map frontend camelCase keys to backend snake_case fields
    key_map = {
        'reporter': 'reporter_name',
        'reporterPhone': 'reporter_phone',
        'reporterRelation': 'reporter_relation',
        'incidentTime': 'incident_time',
        'suspectName': 'suspect_name',
        'suspectDesc': 'suspect_description',
        'victimsInvolved': 'victims_involved',
        'evidencePhotos': 'evidence_photos',
        'evidencePhotoCount': 'evidence_photo_count',
        'isAnonymous': 'is_anonymous',
        'incidentDate': 'incident_date',
        'dateOfIncident': 'incident_date',
        # keep common names
        'details': 'details',
        'category': 'category',
        'subcategory': 'subcategory',
        'location': 'location',
        'urgency': 'urgency',
        'landmark': 'landmark',
    }

    for src, dst in key_map.items():
        if src in data and dst not in data:
            data[dst] = data.pop(src)

    if data.get('reporter_relation'):
        valid_relations = {c[0] for c in Incident.REPORTER_RELATION_CHOICES}
        if data['reporter_relation'] not in valid_relations:
            data['reporter_relation'] = None

    if 'evidence_photos' in data:
        if isinstance(data['evidence_photos'], str):
            data['evidence_photos'] = [data['evidence_photos']]
        elif data['evidence_photos'] is None:
            data['evidence_photos'] = []
        if isinstance(data['evidence_photos'], list):
            data['evidence_photo_count'] = len(data['evidence_photos'])

    if 'evidence_photo_count' in data:
        try:
            data['evidence_photo_count'] = int(data['evidence_photo_count'])
        except (TypeError, ValueError):
            data['evidence_photo_count'] = 0

    urgency = data.get('urgency')
    if urgency and not data.get('priority'):
        urgency_key = str(urgency).strip().lower()
        priority_map = {
            'low': 'low',
            'medium': 'medium',
            'high': 'high',
            'critical': 'high',
        }
        data['priority'] = priority_map.get(urgency_key, 'medium')

    # If anonymous, ensure reporter_name/phone are set appropriately
    is_anon = data.get('is_anonymous')
    if isinstance(is_anon, str):
        is_anon = is_anon.lower() in ('true', '1')
    if is_anon:
        data['reporter_name'] = data.get('reporter_name') or 'Anonymous'
        data['reporter_phone'] = ''

    # Ensure sensible defaults for missing required fields
    data.setdefault('source', 'public')
    data.setdefault('status', 'new')
    data.setdefault('priority', 'medium')

    if data.get('id') and Incident.objects.filter(id=data['id']).exists():
        return Response({"id": ["ID already exists."]}, status=status.HTTP_409_CONFLICT)

    serializer = IncidentSerializer(data=data)
    if serializer.is_valid():
        # ID will be auto-generated by the model
        serializer.save()
        payload = serializer.data
        return Response({
            'success': True,
            'trackingId': payload.get('id'),
            'id': payload.get('id'),
            'report': payload,
        }, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
